### ISSUE TITLE
set up github-changelog-generator to automatically maintain CHANGELOG.md

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-ruby-client#8]
https://github.com/skywinder/github-changelog-generator

**Comment by tyleragreen** [comment]
I added github_changelog_generator to the gemspec and a rough rake task to produce CHANGELOG.md. We may want to add one more level of automation, otherwise, this can be closed.

**Comment by drewda** [comment]
Nice. Thanks, @tyleragreen.
